export default {

  PROFILE_CREATED: 'PROFILE_CREATED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',

  ITEMS_RECEIVED: 'ITEMS_RECEIVED',
  ITEM_ADDED: 'ITEM_ADDED',

  LOCATION_CHANGED: 'LOCATION_CHANGED',

};
