export default {

  PROFILE_CREATED: 'PROFILE_CREATED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',

  ITEMS_RECEIVED: 'ITEMS_RECEIVED',
  ITEM_CREATED: 'ITEM_CREATED',
  // ITEM_ADDED: 'ITEM_ADDED',

  LOCATION_CHANGED: 'LOCATION_CHANGED',

};
